### ISSUE TITLE
Captcha feature request

### ISSUE THREAD

**Issue by Webuser6666** [simon987/ngx_http_js_challenge_module#1]
Tell me, did you google a captcha?

**Comment by simon987** [comment]
I'm not sure I understand the question.

This repository does not involve google recaptcha if that's what you're asking.

**Comment by Webuser6666** [comment]
> I'm not sure I understand the question.
> 
> This repository does not involve google recaptcha if that's what you're asking.

I asked if you have a captcha module?

**Comment by simon987** [comment]
No, this module does not have any captcha

**Comment by Webuser6666** [comment]
> No, this module does not have any captcha

add pls =)

**Comment by simon987** [comment]
I don't indent to integrate captchas in the near future unless I can find a self-contained C/C++ component that can generate a captcha without dependencies. (And I don't intend to integrate google recaptcha ever)
