### ISSUE TITLE
Option for custom http status code

### ISSUE THREAD

**Issue by tobias992** [simon987/ngx_http_js_challenge_module#16]
Hello,

attached one option for 503 http status code. When challenge is active you will get problems with search engine bots (they will index the ddos template). To change the http status code from 200 to better 503 just run the following command before create module:

sed -i 's/NGX_HTTP_OK/NGX_HTTP_SERVICE_UNAVAILABLE/g' /path/to/ngx_http_js_challenge.c

This fix is only interesting for the temporary activation of the challenge. For people who always use the active challenge, this fix is not the best solution (because search engine bots cannot index).

**Comment by bnchdan** [comment]
Hi,
@tobias992 you can add GogleBot IPs in a white list in nginx conf 

https://www.gstatic.com/ipranges/goog.json
https://developers.google.com/search/apis/ipranges/googlebot.json

and you can have something like:

```
http {

    geo $white_user {
        default 0;
        1.2.3.4/32 1;
        4.3.2.1/32 1;
        192.168.0.0/16 1;
    }
    server {
        ...
        js_challenge on;
        js_challenge_secret "test";
        js_challenge_html /var/www/html/loading.html;
        #js_challenge_bucket_duration 600;
        js_challenge_title "Verifying your browser...";
        ...
       location /{
               proxy_pass http://domain.ro/;            
               if ($white_user = 1) { return 599; }
        }
        error_page 599 = @outside;
        location @outside {
            #if ip in white list set challenge to off
            js_challenge off;

            set $upstream http://domain.ro;
            proxy_pass http://domain.ro;
       }

        ...
      }
}
```

**Comment by tobias992** [comment]
Hello @bnchdan 

Thank you for response. But this workaround have security problems. Because it's very easy for an attacker to fake the source ip address or the user agent. I also tried some other configurations. I think the best option is to implement the custom status code inside the module.

I have no idea how to write or edit a nginx module. And when it's a money question i would pay for this feature.

**Comment by bnchdan** [comment]
@tobias992  It is easy to send a TCP packet with any IP address, but  the problem is receiving the SYN/ACK (or any other response), which will be routed to the original IP. Whithout access to the network behind one of the allowed IP addresses or access to a machine behind one of the allowed IP addresses, you can not pass a [TCP 3-way handshake](https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_establishment) with a spoofed IP address. 

I don't know what the 'user agent' does in this context (sure you can pass if the user agent is : "[Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)]")

So, you want to respond with 503 ("service unavailable") if is a google bot? I think you want to allow the google bot to pass the js challenge.

**Comment by tobias992** [comment]
Yes thats true, but nginx have to handle these requests.

I want to use this module only when i have an active attack. I have own scripts wich activate and deactivate the module automatically. When it's active i just want to have the 503 for everyone - this is the same way like cloudflare waf works.

So:
- request to website
- no cookie detected
- 503 with redirect ddos page (js_challenge_html)
- finally redirect to normal page when cookie set - otherwise loop of ddos page

At the moment i have a manual configuration wich works like that. But the cookie is much easier and can easy be parsed. This is the reason why i want to change. But you need a clean 503 http status code when active. Because all search engines don't index when 503 is send.

**Comment by bnchdan** [comment]
1)If you want to change the status code I think you will need to change  
https://github.com/simon987/ngx_http_js_challenge_module/blob/b1c85a625db1629527d2a92c8de7780ff46a5c7c/ngx_http_js_challenge.c#L234

 `   r->headers_out.status = NGX_HTTP_OK;`

    with  

 `   r->headers_out.status =503; //or  r->headers_out.status = "503"; if is string`


2)And

>  the cookie is much easier and can easy be parsed.

  the cookie is calculated here https://github.com/simon987/ngx_http_js_challenge_module/blob/b1c85a625db1629527d2a92c8de7780ff46a5c7c/ngx_http_js_challenge.c#L256 
```
/*
     * Challenge= hex( SHA1( concat(bucket, addr, secret) ) )
     */
    memcpy(buf, p, sizeof(bucket));
    memcpy((buf + sizeof(int32_t)), addr.data, addr.len);
    memcpy((buf + sizeof(int32_t) + addr.len), secret.data, secret.len);

    __sha1((unsigned char *) buf, (size_t) (sizeof(int32_t) + addr.len + secret.len), md);
    buf2hex(md, SHA1_MD_LEN, out);
```
bassed on IP, Secret (js_challenge_secret) and bucket  (js_challenge_bucket_duration)

**Comment by tobias992** [comment]
I mean my actual cookie challenge. This is the reason why i want to change to this module here. In my actual config the cookie value is easy to parse.

Perfect, i found a solution. Before make the module just run the following command. Then you get a clean 503 status code.

sed -i 's/NGX_HTTP_OK/NGX_HTTP_SERVICE_UNAVAILABLE/g' /path/to/ngx_http_js_challenge.c
