### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by tobias992** [simon987/ngx_http_js_challenge_module#24]
When challenge is active, i get the following 3 loglines:

`2022/11/22 13:23:46 [error] 1031502#1031502: *162 [ js challenge log ] sending challenge... , client: 123.123.123, server: mydomain.de, request: "GET / HTTP/2.0", host: "mydomain.de"`
`2022/11/22 13:23:47 [error] 1031501#1031501: *164 [ js challenge log ] sending challenge... , client: 123.123.123, server: mydomain.de, request: "GET /apple-touch-icon-precomposed.png HTTP/2.0", host: "mydomain.de"`
`2022/11/22 13:23:47 [error] 1031501#1031501: *164 [ js challenge log ] sending challenge... , client: 123.123.123, server: mydomain.de, request: "GET /apple-touch-icon.png HTTP/2.0", host: "mydomain.de"`

Maybe there is a way to remove these 2 unneeded safari lines.

Workaround for max performance is to set error_log level to "crit" - then you don't have logging.

**Comment by tobias992** [comment]
Thank you. But for me the best solution is to set the error_log level to crit. I just need max performance in case of an attack. And saving millions of loglines saves a lot of io.

**Comment by bnchdan** [comment]
Nonsens. Can we close the issue?

**Comment by tobias992** [comment]
Nonsens? Sorry but i have no idea who you are. But i work every day in hosting business and also with a lot of ddos attacks.

So when you think, saving millions of loglines doesn't improve system performance, then you are just a coder and have no experience in real life usage.
